
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE                0
#define PARTNER_STEVEN              1
#define PARTNER_PEPPER_NUSI_01      2
#define PARTNER_PEPPER_NUSI_02      3
#define PARTNER_PEPPER_NUSI_03      4
#define PARTNER_PEPPER_NUSI_04      5
#define PARTNER_PEPPER_NUSI_05      6
#define PARTNER_SISTER_ONITAIZI     7

// Reverse Path
#define PARTNER_DONDOGIRI_REVERSE      8
#define PARTNER_GREAT_TREADS_REVERSE   9
#define PARTNER_ORTHWORM_REVERSE      10
#define PARTNER_BOMBIRDIER_REVERSE    11
#define PARTNER_KLAWF_REVERSE         12

#define PARTNER_COUNT 13

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
