gText_Birch_Welcome::
	.string "Welcome to {COLOR RED}Scrambled Scarlet{COLOR DARK_GRAY}!\p"
	.string "This isn't your traditional RomHack…\p"
	.string "{COLOR RED}EVERY{COLOR DARK_GRAY} single POKéMON has been\n"
	.string "reimagined with thoughtful buffs and\l"
	.string "changes to make them fun and\l"
	.string "satisfying to use!\p"
	.string "You can use your favorites and win\n"
	.string "with the right preperation!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Each Pokémon gets 3 amazing abilities,\n"
	.string "reworked moves, terastalization,\l"
	.string "tons of items & more!\p"
	.string "It's balanced around {COLOR RED}Teamlocked{COLOR DARK_GRAY}\n"
	.string "{COLOR RED}Nuzlocke{COLOR DARK_GRAY}, a format where you don't\l"
	.string "swap out team members unless one dies.\p"
	.string "It's meant for you to bond with your\n"
	.string "team and not carelessly sack them!\p"
	.string "{COLOR RED}Teamlocke{COLOR DARK_GRAY} is fun and encouraged,\n"
	.string "but it's {COLOR RED}TOTALLY optional{COLOR DARK_GRAY}.\p"
	.string "Please, USE THE {COLOR RED}DOOZDEX{COLOR DARK_GRAY} - it's a tool\n"
	.string "designed to answer all of your\l"
	.string "questions about the game.\p"
	.string "If you need extra help or are stuck,\n"
	.string "join the Discord server!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Alright, now let's begin…$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, one more thing.\p"
	.string "This romhack is currently in\n"
	.string "alpha.\p"
	.string "Refer to the doozdex for\n"
	.string "more info on trainers and eggs.\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
