[package]
name = "pokeemerald-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec.version = "0.7.6"
arrayvec.default-features = false

[lib]
crate-type=["staticlib"]

[build-dependencies]
bindgen = "0.71.1"
